package html

var (
	ErrorInvalidHtmlTag                    = -1
	ErrorInvalidOrUnsupportedHtmlAttribute = 0
	ValidHtmlAttribute                     = 1
)

var htmlTags = map[string]bool{
	"a":          true,
	"abbr":       true,
	"address":    true,
	"area":       true,
	"article":    true,
	"aside":      true,
	"audio":      true,
	"b":          true,
	"base":       true,
	"bdi":        true,
	"bdo":        true,
	"blockquote": true,
	"body":       true,
	"br":         true,
	"button":     true,
	"canvas":     true,
	"caption":    true,
	"cite":       true,
	"code":       true,
	"col":        true,
	"colgroup":   true,
	"data":       true,
	"datalist":   true,
	"dd":         true,
	"del":        true,
	"details":    true,
	"dfn":        true,
	"dialog":     true,
	"div":        true,
	"dl":         true,
	"dt":         true,
	"em":         true,
	"embed":      true,
	"fieldset":   true,
	"figcaption": true,
	"figure":     true,
	"footer":     true,
	"form":       true,
	"h1":         true,
	"head":       true,
	"header":     true,
	"hgroup":     true,
	"hr":         true,
	"html":       true,
	"i":          true,
	"iframe":     true,
	"img":        true,
	"input":      true,
	"ins":        true,
	"kbd":        true,
	"label":      true,
	"legend":     true,
	"li":         true,
	"link":       true,
	"main":       true,
	"map":        true,
	"mark":       true,
	"MathML":     true,
	"menu":       true,
	"meta":       true,
	"meter":      true,
	"nav":        true,
	"noscript":   true,
	"object":     true,
	"ol":         true,
	"optgroup":   true,
	"option":     true,
	"output":     true,
	"p":          true,
	"param":      true,
	"picture":    true,
	"pre":        true,
	"progress":   true,
	"q":          true,
	"rp":         true,
	"rt":         true,
	"ruby":       true,
	"s":          true,
	"samp":       true,
	"script":     true,
	"section":    true,
	"select":     true,
	"slot":       true,
	"small":      true,
	"source":     true,
	"span":       true,
	"strong":     true,
	"style":      true,
	"sub":        true,
	"summary":    true,
	"sup":        true,
	"svg":        true,
	"table":      true,
	"tbody":      true,
	"td":         true,
	"template":   true,
	"textarea":   true,
	"tfoot":      true,
	"th":         true,
	"thead":      true,
	"time":       true,
	"title":      true,
	"tr":         true,
	"track":      true,
	"u":          true,
	"ul":         true,
	"var":        true,
	"video":      true,
	"wbr":        true,
}

var htmlGlobalAttributes = map[string]bool{
	"accesskey":       true,
	"autocapitalize":  true,
	"autofocus":       true,
	"contenteditable": true,
	"dir":             true,
	"draggable":       true,
	"enterkeyhint":    true,
	"hidden":          true,
	"inputmode":       true,
	"is":              true,
	"itemid":          true,
	"itemprop":        true,
	"itemref":         true,
	"itemscope":       true,
	"itemtype":        true,
	"lang":            true,
	"nonce":           true,
	"spellcheck":      true,
	"style":           true,
	"tabindex":        true,
	"title":           true,
	"translate":       true,
}

var htmlAttributes = map[string]map[string]bool{
	"a": {
		"href":           true,
		"target":         true,
		"download":       true,
		"ping":           true,
		"rel":            true,
		"hreflang":       true,
		"type":           true,
		"referrerpolicy": true,
	},
	"area": {
		"alt":            true,
		"coords":         true,
		"shape":          true,
		"href":           true,
		"target":         true,
		"download":       true,
		"ping":           true,
		"rel":            true,
		"referrerpolicy": true,
	},
	"audio": {
		"src":         true,
		"crossorigin": true,
		"preload":     true,
		"autoplay":    true,
		"loop":        true,
		"muted":       true,
		"controls":    true,
	},
	"base": {
		"href":   true,
		"target": true,
	},
	"blockquote": {
		"cite": true,
	},
	"body": {
		"onafterprint":         true,
		"onbeforeprint":        true,
		"onbeforeunload":       true,
		"onhashchange":         true,
		"onlanguagechange":     true,
		"onmessage":            true,
		"onmessageerror":       true,
		"onoffline":            true,
		"ononline":             true,
		"onpagehide":           true,
		"onpageshow":           true,
		"onpopstate":           true,
		"onrejectionhandled":   true,
		"onstorage":            true,
		"onunhandledrejection": true,
		"onunload":             true,
	},
	"button": {
		"disabled":       true,
		"form":           true,
		"formaction":     true,
		"formenctype":    true,
		"formmethod":     true,
		"formnovalidate": true,
		"formtarget":     true,
		"name":           true,
		"type":           true,
		"value":          true,
	},
	"canvas": {
		"width":  true,
		"height": true,
	},
	"col": {
		"span": true,
	},
	"colgroup": {
		"span": true,
	},
	"data": {
		"value": true,
	},
	"del": {
		"cite":     true,
		"datetime": true,
	},
	"details": {
		"open": true,
	},
	"dialog": {
		"open": true,
	},
	"embed": {
		"src":    true,
		"type":   true,
		"width":  true,
		"height": true,
	},
	"fieldset": {
		"disabled": true,
		"form":     true,
		"name":     true,
	},
	"form": {
		"accept-charset": true,
		"action":         true,
		"autocomplete":   true,
		"enctype":        true,
		"method":         true,
		"name":           true,
		"novalidate":     true,
		"target":         true,
	},
	"html": {
		"manifest": true,
	},
	"iframe": {
		"src":             true,
		"srcdoc":          true,
		"name":            true,
		"sandbox":         true,
		"allow":           true,
		"allowfullscreen": true,
		"width":           true,
		"height":          true,
		"referrerpolicy":  true,
		"loading":         true,
	},
	"img": {
		"alt":            true,
		"src":            true,
		"srcset":         true,
		"sizes":          true,
		"crossorigin":    true,
		"usemap":         true,
		"ismap":          true,
		"width":          true,
		"height":         true,
		"referrerpolicy": true,
		"decoding":       true,
		"loading":        true,
	},
	"input": {
		"accept":         true,
		"alt":            true,
		"autocomplete":   true,
		"checked":        true,
		"dirname":        true,
		"disabled":       true,
		"form":           true,
		"formaction":     true,
		"formenctype":    true,
		"formmethod":     true,
		"formnovalidate": true,
		"formtarget":     true,
		"height":         true,
		"list":           true,
		"max":            true,
		"maxlength":      true,
		"min":            true,
		"minlength":      true,
		"multiple":       true,
		"name":           true,
		"pattern":        true,
		"placeholder":    true,
		"readonly":       true,
		"required":       true,
		"size":           true,
		"src":            true,
		"step":           true,
		"type":           true,
		"value":          true,
		"width":          true,
	},
	"ins": {
		"cite":     true,
		"datetime": true,
	},
	"label": {
		"for": true,
	},
	"li": {
		"value": true,
	},
	"link": {
		"href":           true,
		"crossorigin":    true,
		"rel":            true,
		"as":             true,
		"media":          true,
		"hreflang":       true,
		"type":           true,
		"sizes":          true,
		"imagesrcset":    true,
		"imagesizes":     true,
		"referrerpolicy": true,
		"integrity":      true,
		"blocking":       true,
		"color":          true,
		"disabled":       true,
	},
	"map": {
		"name": true,
	},
	"meta": {
		"name":       true,
		"http-equiv": true,
		"content":    true,
		"charset":    true,
		"media":      true,
	},
	"meter": {
		"value":   true,
		"min":     true,
		"max":     true,
		"low":     true,
		"high":    true,
		"optimum": true,
	},
	"object": {
		"data":   true,
		"type":   true,
		"name":   true,
		"form":   true,
		"width":  true,
		"height": true,
	},
	"ol": {
		"reversed": true,
		"start":    true,
		"type":     true,
	},
	"optgroup": {
		"disabled": true,
		"label":    true,
	},
	"option": {
		"disabled": true,
		"label":    true,
		"selected": true,
		"value":    true,
	},
	"output": {
		"for":  true,
		"form": true,
		"name": true,
	},
	"param": {
		"name":  true,
		"value": true,
	},
	"progress": {
		"value": true,
		"max":   true,
	},
	"q": {
		"cite": true,
	},
	"script": {
		"src":            true,
		"type":           true,
		"async":          true,
		"defer":          true,
		"crossorigin":    true,
		"integrity":      true,
		"referrerpolicy": true,
		"blocking":       true,
	},
	"select": {
		"autocomplete": true,
		"disabled":     true,
		"form":         true,
		"multiple":     true,
		"name":         true,
		"required":     true,
		"size":         true,
	},
	"slot": {
		"name": true,
	},
	"source": {
		"src":    true,
		"type":   true,
		"srcset": true,
		"sizes":  true,
		"media":  true,
		"width":  true,
		"height": true,
	},
	"style": {
		"media":    true,
		"blocking": true,
	},
	"td": {
		"colspan": true,
		"rowspan": true,
		"headers": true,
	},
	"textarea": {
		"cols":        true,
		"dirname":     true,
		"disabled":    true,
		"form":        true,
		"maxlength":   true,
		"minlength":   true,
		"name":        true,
		"placeholder": true,
		"readonly":    true,
		"required":    true,
		"rows":        true,
		"wrap":        true,
	},
	"th": {
		"colspan": true,
		"rowspan": true,
		"headers": true,
		"scope":   true,
		"abbr":    true,
	},
	"time": {
		"datetime": true,
	},
	"track": {
		"default": true,
		"kind":    true,
		"label":   true,
		"src":     true,
		"srclang": true,
	},
	"video": {
		"src":         true,
		"crossorigin": true,
		"poster":      true,
		"preload":     true,
		"autoplay":    true,
		"playsinline": true,
		"loop":        true,
		"muted":       true,
		"controls":    true,
		"width":       true,
		"height":      true,
	},
}

// IsValidHTMLTag validate whether an input string is a valid HTML Tag
func IsValidHTMLTag(tag string) bool {
	return htmlTags[tag]
}

// IsValidHTMLAttribute validate whether an input string is a valid HTML attribute depends on input tag
// Error integer code on false result represents one of reason:
// -2: invalid HTML tag,
// -1: invalid HTML attribute,
//  0: unsupported HTML attribute
func IsValidHTMLAttribute(tag string, attr string) (bool, int) {
	if htmlGlobalAttributes[attr] {
		return true, ValidHtmlAttribute
	}

	if !IsValidHTMLTag(tag) {
		return false, ErrorInvalidHtmlTag
	}

	attrs, exist := htmlAttributes[tag]
	if !exist {
		return false, ErrorInvalidOrUnsupportedHtmlAttribute
	}

	isValidAttr := attrs[attr]
	if isValidAttr {
		return true, ValidHtmlAttribute
	} else {
		return false, ErrorInvalidOrUnsupportedHtmlAttribute
	}
}
